apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-green
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: example_code
        color: green
    spec:
      containers:
      - name: simple_web
        image: bubri.azurecr.io/simple_web
        ports:
        - containerPort: 80