apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-red
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        color: red
    spec:
      containers:
      - name: nginx
        image: bubriks/simple_web
        ports:
        - containerPort: 80