apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: katacoda-grafana
  namespace: istio-system
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
  selector:
    app: grafana
  type: ClusterIP
  externalIPs:
    - 172.17.0.54
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: prometheus
  name: katacoda-prometheus
  namespace: istio-system
spec:
  ports:
  - name: http-prometheus
    port: 9090
    protocol: TCP
  selector:
    app: prometheus
  type: ClusterIP
  externalIPs:
    - 172.17.0.54