name: Docker Image CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: Azure/docker-login@v1
      with:
        login-server: bubri.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build . -t bubri.azurecr.io/k8sdemo:${{ github.sha }}
        docker push bubri.azurecr.io/k8sdemo:${{ github.sha }}
    
    # Set the target AKS cluster.
    - uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: bubri
        resource-group: bubri-rg

    - uses: Azure/k8s-create-secret@v1
      with:
        container-registry-url: bubri.azurecr.io
        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        secret-name: demo-k8s-secret

    - uses: Azure/k8s-deploy@v1.4
      with:
        manifests: |
          deployment.yml
        images: |
          demo.azurecr.io/k8sdemo:${{ github.sha }}
        imagepullsecrets: |
          demo-k8s-secret